name: copinstar-pong

services:

  server:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    ports:
      - 51009:51009/tcp
      - 51009:51009/udp
    restart: unless-stopped
      